name: Deploy Nuget

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    
    - name: Run NUnit Tests
      run: dotnet test SatImageUtilities.Tests

    - name: Build solution and generate NuGet package
      run: dotnet build SatImageUtilities -c Release -o nupkgs

    - name: Tag commit
      uses: ataboo/csproj-tag-action@using-js-instead 
      with: 
        token: ${{secrets.GITHUB_TOKEN}}

    - name: Install NuGet client
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/ataboo/index.json -Username ataboo -Password ${{secrets.GITHUB_TOKEN}}
    
    - name: Push NuGet package to GitHub
      run: nuget push .\nupkgs\*.nupkg -Source "GPR" -SkipDuplicate
