on: 
  push:
    branches-ignore:
      - 'master'

jobs:
  build_and_test:
    runs-on: windows-latest
    name: NUnit Test
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Build Project
      run: dotnet build SatImageUtilities.Tests
    - name: Run NUnit Tests
      run: dotnet test SatImageUtilities.Tests
