name: Testing Versioning

on: 
  push:
    branches-ignore:
      - 'master'

jobs:
  build_and_test:
    runs-on: windows-latest
    name: Try to echo version
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Build Project
      run: dotnet build SatImageUtilities.Tests
    - name: Echo Version
      run: echo [Version] $xml.Project.PropertyGroup.Version
    
